### ISSUE TITLE
Feature Request: Version Number

### ISSUE THREAD

**Issue by VendettaMike** [certera-io/certera#13]
Your software was exactly what I needed for managing LE certificates in my homelab. Thanks for sharing! 
One thing I found missing was that the version number is only available in a txt file. It would be nice to have it displayed on the settings page or on an about page that shows your software details, contact, etc.

**Comment by certeraio** [comment]
Hi @VendettaMike!

I'm glad you found it useful. Ya, I agree on that version number thing. I've thought the same thing myself in the past. I'll get this on the list of things to add for the next release.
