### ISSUE TITLE
Notifications not sent but test email is working (non SSL connection to mail server)

### ISSUE THREAD

**Issue by gik000** [certera-io/certera#21]
The notifications are not sent, but I can successfully receive the test email.

That is very strange.

The only think I can suppose about it is that we are not working under SSL connection (to the mail server).

**Comment by certeraio** [comment]
That is indeed strange. If you can receive a test email, you should definitely be getting the other notifications. Can you confirm the SMTP configuration on the "Settings" page, please? Also can you provide a screenshot of your Notifications page (should it not contain a Slack Webhook URL), please?

**Comment by gik000** [comment]
The problem is when you set alternative emails.

If there is only one mail  (i.e. in "Recipients" field), everything works fine,
on the other hand if you put 2 email (I tested with 2 addresses),
whether are " ; " separated or ";" (with no space between) the notification is not send.
