### ISSUE TITLE
No ADD button on certificate creation page

### ISSUE THREAD

**Issue by gik000** [certera-io/certera#6]
There is no ADD (or CREATE) button on certificate creation page.
Being a standard html form it is possible to submit the form putting the focus on a textfield and hitting "Enter" button.

**Comment by certeraio** [comment]
Hi @gik000,

There's a button "CREATE" at the very bottom, below the CSR details.

![image](https://user-images.githubusercontent.com/56412151/81837217-6f1a8d00-94f9-11ea-9d17-7aec3a626858.png)

Also, when I enter a text input field and hit "Enter" on my keyboard, the form is submitted. What browser, device, OS, etc. are you using?

**Comment by gik000** [comment]
Hi

Ubuntu/firefox

![immagine](https://user-images.githubusercontent.com/1844358/81938673-86d73b80-95f5-11ea-8346-e9d5f87fd10f.png)

you can see the image 

version 1.5.0

**Comment by certeraio** [comment]
Hi @gik000,

It's indeed a bug. I was able to replicate the issue with Firefox. I've made an updated version 2.1.1-beta that contains a fix located here: https://github.com/certera-io/certera/releases/tag/2.1.1-beta
