### ISSUE TITLE
Test email feature

### ISSUE THREAD

**Issue by gik000** [certera-io/certera#7]
It would be very nice to have the possibility to test the email sending.

In other words it would be better to be aware of some email troubles before the notification is normally  triggered.

**Comment by certeraio** [comment]
Hi @gik000,

Thanks for the recommendation. I had the same thought a while back. I'll get that added into the next release!

**Comment by certeraio** [comment]
FYI, finally got around to getting this done in this release: https://github.com/certera-io/certera/releases/tag/2.1.3
