### ISSUE TITLE
Chain parameter TRUE/FALSE does not work like expected

### ISSUE THREAD

**Issue by gik000** [certera-io/certera#8]
To obtain the certificate (not the chain, nor the private key one),
it should be necessary to add the parameter -d "chain=false", but this parameter is always ignored (v. 1.5.0) and the certificate is always in "Chain" mode.

It is not a blocking issue, because the first piece of the chain certificate corresponds to the main one, so it can be easily overcome.

**Comment by certeraio** [comment]
Hi @gik000,

The chain parameter was only added in version 2.0.2-beta. Keep an eye out for the changes in each release. (I recommend changing the notification settings to "Releases only" or "Watching", if you haven't set that already). :)

https://github.com/certera-io/certera/releases
